export const Ary = [{id:1, path:'/', category:'All Categories'}, 
{id:2, path: 'smartphones', category:'SmartPhones'}, 
{id:3, path: 'laptops', category:'Laptops'},
     {id:4, path: 'skincare', category:'Skincare'}, 
    {id:5, path: 'grocery', category:'Groceries'},
    {id:6, path: 'fragrances', category:'Fragrances'},
     {id:7, path: 'decoration', category:'Home-Decoration'},
      {id:8, path: 'furniture', category:'Furniture'}, 
      {id:9, path: 'womens-dresses', category:'Womens-Fashion'}, 
     {id:10, path: 'womens-shoes', category:'Womens-Shoes'}, 
     {id:11, path: 'tshirts', category:'Mens T-shirts'}, 
     {id:12, path: 'mens-shoes', category:'Mens-Shoes'},
    {id:13, path: 'mens-watches', category:'Mens-Watches'}, 
    {id:14, path: 'womens-watches', category:'Womens-Watches'}, 
    {id:15, path: 'womens-bags', category:'Womens-Bags'}, 
    {id:16, path: 'jewellery', category:'Womens-Jewellery'}, 
    {id:17, path: 'sunglass', category:'Sunglasses'}, 
    {id:18, path: 'automotive', category:'Automotive-Parts'},
    {id:19, path: 'motorcycle', category:'Motorcycle'}, 
    {id:20, path: 'lighting', category:'Lighting'}]